### ISSUE TITLE
CWE-WASC mapping

### ISSUE THREAD

**Issue by anubhavchitrey** [KennaPublicSamples/All_Samples#39]
Checkmarx identifies many vulnerability categories which have no mapping to WASC id. The script stops if the mapping is not found hard-coded dictionary in the script. How to deal with such situation? I have Checkmarx scan results with CWE ids which are not mapped to WASC id.

**Comment by lindambrown** [comment]
we now have a checkmarx connector so you should use the native connector instead. Otherwise, you can add to the items in the code itself.
